### ISSUE TITLE
Password Complexity Check

### ISSUE THREAD

**Issue by DerekDVS** [emcphee/Fintech-DLP-testbed#5]
Passwords complexity logic function has been done but the implementation and enforcement has not.

**Comment by JeanCho** [comment]
I thought i committted to main time ago but think got overwritten.. I'll make it work again

**Comment by JeanCho** [comment]
Here is code but  pylint thing is troubling me so can anyone test this, it should work like last time i did:


def register(request):

    db_connection = connections['default']
    cursor = db_connection.cursor()
    error_message = None  # Initialize error message to None

    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password_confirm = request.POST['password_confirm']

        # Check for password strength
        if not is_strong_password(password):
            error_message = "Password is not strong enough."
        elif password != password_confirm:
            error_message = "Confirmed password must match the password."
        elif not email or Client.objects.filter(username=username).exists():
            error_message = "Email or username already exists."
        else:
            salt = bcrypt.gensalt()
            hashed_password = bcrypt.hashpw(password.encode('utf-8'), salt)

            # Create a new client
            new_item = Client(username=username, email=email, salt=salt.decode('utf-8'), hashed_password=hashed_password.decode('utf-8'))
            new_item.save()
            new_account = BankAccount(client_id=new_item, savings=0)
            new_account.save()

            # Redirect to a success page or home page
            return home(request)

    page_args = {
        "error_message": error_message,
        'is_logged_in': ('username' in request.session)
    }
    return render(request, "register.html", page_args)

**Comment by DerekDVS** [comment]
Password check is enforced.
